GIT_ACCOUNT:
  USER: 
  PASS: 
NOTIFY_TO_EMAIL: 
NOTIFY_TO_NAME: 
NOTIFY_FROM_EMAIL: 
NOTIFY_FROM_NAME: 
ALERT_TO_EMAIL: 
WEBSITE: 
INTERVAL: 60
DEBUG: 1
COMMANDS_WHEN_SERVER_GOES_DOWN:
  - ls
  - echo 'hi'